### ISSUE TITLE
Automatic redirect miner address

### ISSUE THREAD

**Issue by ethereumpy** [LostSoulFly/MinerProxy#10]
Can you implement automatic miner address redirection ? only keep DevFee functional as it is
Thanks

**Comment by LostSoulFly** [comment]
I'm not sure what you mean by "automatic miner address redirection"?

**Comment by ethereumpy** [comment]
keep  "walletAddress": " " blank so it can mine directly to miner's wallet address

**Comment by LostSoulFly** [comment]
That should be easy enough -- just remove the empty wallet check in
Settings.cs. I don't have a way to test this as I don't solo mine, but that
would probably work.

**Comment by ethereumpy** [comment]
after removing empty wallet check in, the all miner authenticate as DevFee no matter what change i make
please help

**Comment by LostSoulFly** [comment]
Which coin are you mining?

**Comment by ethereumpy** [comment]
ETH

**Comment by LostSoulFly** [comment]
I can't see why it wouldn't work by looking at the source.

This is assuming your miners use a blank wallet address, with no rigName (
wallet.rig1 or wallet/rig1).. Just a completely empty address.
You've got identifyDevFee turned on.

See this: if the wallet address that was sent by the miner matches the
wallet address that you want to replace, it's considered NOT a devfee.
Otherwise, it's considered a devfee. So the wallet address being blank
would have to actually be blank, meaning it couldn't contain anything else
at all.

https://github.com/LostSoulFly/MinerProxy/blob/4f7d74ee321ab00e01ad9bbd52d7ef8dc6b958b0/MinerProxy/CoinHandlers/EthCoin.cs#L80
